#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from pathlib import Path

import numpy as np

from crosscoder_common import (
    compute_latent_summary,
    index_activation_files,
    load_checkpoint_encoder,
    load_layer,
    read_jsonl,
    result_key,
)


def binary_roc_auc(y_true: np.ndarray, scores: np.ndarray) -> float:
    """
    ROC-AUC via Mann-Whitney U, implemented only with NumPy.

    Handles tied scores using average ranks.
    Labels:
        0 = passed tests
        1 = failed tests
    """
    y_true = np.asarray(y_true, dtype=np.int8)
    scores = np.asarray(scores, dtype=np.float64)

    if y_true.ndim != 1 or scores.ndim != 1:
        raise ValueError("y_true and scores must be one-dimensional")

    if len(y_true) != len(scores):
        raise ValueError("y_true and scores must have equal length")

    positive = y_true == 1
    negative = y_true == 0

    n_positive = int(positive.sum())
    n_negative = int(negative.sum())

    if n_positive == 0 or n_negative == 0:
        raise ValueError(
            "ROC-AUC requires at least one passing and one failing example"
        )

    order = np.argsort(scores, kind="mergesort")
    sorted_scores = scores[order]

    ranks = np.empty(len(scores), dtype=np.float64)

    start = 0
    while start < len(scores):
        end = start + 1

        while (
            end < len(scores)
            and sorted_scores[end] == sorted_scores[start]
        ):
            end += 1

        # Ranks are one-based. Tied values receive their average rank.
        average_rank = ((start + 1) + end) / 2.0
        ranks[order[start:end]] = average_rank

        start = end

    rank_sum_positive = float(ranks[positive].sum())

    auc = (
        rank_sum_positive
        - n_positive * (n_positive + 1) / 2.0
    ) / (n_positive * n_negative)

    return float(auc)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Offline screening of CrossCoder dimensions against test failure."
    )
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--activation-root", type=Path, required=True)
    parser.add_argument("--results-jsonl", type=Path, required=True, nargs="+")
    parser.add_argument("--model-a", required=True)
    parser.add_argument("--model-b", required=True)
    parser.add_argument("--target-model", required=True)
    parser.add_argument("--layer", type=int, required=True)
    parser.add_argument(
        "--aggregation",
        choices=["max", "mean", "last", "mean_positive"],
        default="max",
    )
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--max-examples", type=int, default=None)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--skip-errors", action="store_true")

    parser.add_argument(
        "--labels-csv",
        type=Path,
        required=True,
        help="CSV generated by tools/build_auc_labels.py",
    )

    parser.add_argument(
        "--model",
        required=True,
        help="Model name used in the labels CSV, e.g. deepseek_base",
    )

    parser.add_argument(
        "--benchmark",
        default="bigcodebench",
        help="Benchmark name used in the labels CSV",
    )

    return parser.parse_args()


def load_auc_labels_csv(path):
    path = Path(path)
    labels = {}

    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)

        required = {
            "model",
            "benchmark",
            "task_id",
            "generation_idx",
            "label",
        }

        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(
                f"{path}: missing required columns: {sorted(missing)}"
            )

        for row in reader:
            key = (
                row["model"].strip(),
                row["benchmark"].strip().lower(),
                row["task_id"].strip(),
                int(row["generation_idx"]),
            )

            if key in labels:
                raise ValueError(f"Duplicate label key: {key}")

            labels[key] = int(row["label"])

    return labels


def main() -> int:
    args = parse_args()
    started = time.perf_counter()

    if args.target_model not in {args.model_a, args.model_b}:
        raise ValueError("--target-model must equal --model-a or --model-b")

    encoder_weight, encoder_bias, ckpt_config = load_checkpoint_encoder(args.checkpoint)
    if encoder_weight.shape[1] != 8192:
        raise ValueError(
            f"Expected encoder input width 8192, got {tuple(encoder_weight.shape)}"
        )

    index_a = index_activation_files(args.activation_root, args.model_a)
    index_b = index_activation_files(args.activation_root, args.model_b)

    rows = []
    for path in args.results_jsonl:
        rows.extend(read_jsonl(path))

    rows = [r for r in rows if r.get("model_label") == args.target_model]
    rows.sort(key=lambda r: (r["benchmark"], int(r["task_idx"]), int(r.get("gen_idx", 0))))
    if args.max_examples is not None:
        rows = rows[: args.max_examples]

    feature_rows: list[np.ndarray] = []
    labels: list[int] = []
    metadata: list[dict] = []
    skipped: list[dict] = []

    total = len(rows)
    for idx, row in enumerate(rows, 1):
        key = result_key(row)
        try:
            path_a = index_a[key]
            path_b = index_b[key]
            activation_a = load_layer(path_a, args.layer)
            activation_b = load_layer(path_b, args.layer)
            summary = compute_latent_summary(
                activation_a,
                activation_b,
                encoder_weight,
                encoder_bias,
                args.aggregation,
                args.device,
            )
        except Exception as exc:
            if not args.skip_errors:
                raise
            skipped.append({"key": repr(key), "error": f"{type(exc).__name__}: {exc}"})
            continue

        correct = bool(row["correct"])
        feature_rows.append(summary)
        labels.append(int(not correct))
        metadata.append(
            {
                "benchmark": key.benchmark,
                "task_idx": key.task_idx,
                "task_id": row.get("task_id"),
                "gen_idx": key.gen_idx,
                "run_id": row.get("run_id"),
                "model_label": row.get("model_label"),
                "correct": correct,
                "failure": int(not correct),
                "activation_a": str(path_a),
                "activation_b": str(path_b),
            }
        )
        if idx == 1 or idx % 25 == 0 or idx == total:
            elapsed = time.perf_counter() - started
            rate = idx / elapsed if elapsed > 0 else 0.0
            eta = (total - idx) / rate if rate > 0 else float("nan")
            print(
                f"[{idx}/{total}] kept={len(feature_rows)} skipped={len(skipped)} "
                f"elapsed={elapsed:.1f}s eta={eta:.1f}s",
                flush=True,
            )

    if not feature_rows:
        raise RuntimeError("No examples were successfully processed")

    X = np.stack(feature_rows)
    y = np.asarray(labels, dtype=np.int8)
    if np.unique(y).size < 2:
        raise RuntimeError(
            f"AUC requires both pass and fail examples; observed labels={np.unique(y).tolist()}"
        )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        args.output_dir / "features.npz",
        X=X,
        y=y,
        feature_ids=np.arange(X.shape[1], dtype=np.int32),
    )

    with (args.output_dir / "examples.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(metadata[0].keys()))
        writer.writeheader()
        writer.writerows(metadata)

    if skipped:
        (args.output_dir / "skipped.json").write_text(
            json.dumps(skipped, indent=2), encoding="utf-8"
        )

    auc_rows = []
    for feature_id in range(X.shape[1]):
        scores = X[:, feature_id]
        if np.all(scores == scores[0]):
            auc = 0.5
        else:
            auc = binary_roc_auc(y, scores)
        predictive_auc = max(auc, 1.0 - auc)
        direction = "positive" if auc >= 0.5 else "negative"
        auc_rows.append(
            {
                "feature_id": feature_id,
                "auc": auc,
                "predictive_auc": predictive_auc,
                "direction": direction,
                "mean_pass": float(scores[y == 0].mean()),
                "mean_fail": float(scores[y == 1].mean()),
                "nonzero_rate": float(np.mean(scores != 0)),
                "n_examples": int(len(y)),
                "n_failures": int(y.sum()),
                "failure_rate": float(y.mean()),
            }
        )

    auc_rows.sort(key=lambda r: r["predictive_auc"], reverse=True)
    with (args.output_dir / "auc_ranking.csv").open(
        "w", encoding="utf-8", newline=""
    ) as handle:
        writer = csv.DictWriter(handle, fieldnames=list(auc_rows[0].keys()))
        writer.writeheader()
        writer.writerows(auc_rows)

    summary = {
        "checkpoint": str(args.checkpoint),
        "checkpoint_config": ckpt_config,
        "model_a": args.model_a,
        "model_b": args.model_b,
        "target_model": args.target_model,
        "layer": args.layer,
        "aggregation": args.aggregation,
        "n_examples": int(len(y)),
        "n_failures": int(y.sum()),
        "failure_rate": float(y.mean()),
        "n_skipped": len(skipped),
        "latent_dim": int(X.shape[1]),
        "elapsed_seconds": time.perf_counter() - started,
        "top_20": auc_rows[:20],
    }
    (args.output_dir / "summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
